### ISSUE TITLE
`org.openrewrite.staticanalysis.ReplaceApacheCommonsLang3ValidateNotNullWithObjectsRequireNonNull` misses calls with argument type other than Object

### ISSUE THREAD

**Issue by Riggs333** [openrewrite/rewrite-static-analysis#457]
## What version of OpenRewrite are you using?

I am using
- rewrite-static-analysis v2.1.0

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>6.0.5</version>
  <configuration>
    ... 
  </configuration>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

Adapting the test case [org.openrewrite.staticanalysis.ReplaceApacheCommonsLang3ValidateNotNullWithObjectsRequireNonNullTest#replaceWithOneArgument
](https://github.com/openrewrite/rewrite-static-analysis/blob/09ea6c0711ef4abe9a38f9bec6729edb62ae66ba/src/test/java/org/openrewrite/staticanalysis/ReplaceApacheCommonsLang3ValidateNotNullWithObjectsRequireNonNullTest.java#L59) by changing the parameter type from `Object` to `String` as an example:

```java
import org.apache.commons.lang3.Validate;

class Test {
    void test(String obj) {
        Validate.notNull(obj);
    }
}
```

## What did you expect to see?

```java
import java.util.Objects;

class Test {
    void test(String obj) {
        Objects.requireNonNull(obj);
    }
}
```

## What did you see instead?

no changes to the code at all

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I'd be happy to help here, but I'm just starting to get an understanding. 😊 

While looking at the source code and playing around, I suspect the following recipe has to be changed:

https://github.com/openrewrite/rewrite-static-analysis/blob/09ea6c0711ef4abe9a38f9bec6729edb62ae66ba/src/main/resources/META-INF/rewrite/java-best-practices.yml#L45-L54

My first naive try was to change the `Object` parameter to `*`, but that does not seem to have an effect:
```yaml
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.apache.commons.lang3.Validate notNull(*)
      newMethodName: requireNonNull
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.commons.lang3.Validate requireNonNull(*)
      fullyQualifiedTargetTypeName: java.util.Objects
```

For me to be sure that the recipe is applied at all, I changed the `Object` parameter to `String` and with that the test case is successful:
```yaml
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.apache.commons.lang3.Validate notNull(String)
      newMethodName: requireNonNull
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.apache.commons.lang3.Validate requireNonNull(String)
      fullyQualifiedTargetTypeName: java.util.Objects
```

So by now I do not have a clue how to fix it, yet.  😄
