### ISSUE TITLE
Replace Arrays.asList

### ISSUE THREAD

**Issue by kthoms** [openrewrite/rewrite-static-analysis#465]
## What problem are you trying to solve?

IJ IDEA issues warnings for usages of `Arrays#asList()` with a single argument.

## What precondition(s) should be checked before applying this recipe?

Java language level should be at least 9

## Describe the situation before applying the recipe

```java
import java.util.Arrays;

class A {
  void foo() {
    Arrays.asList("foo", "bar");
  }
}
```

## Describe the situation after applying the recipe

```java
import java.util.List;

class A {
  void foo() {
    List.of("foo", "bar");
  }
}
```

## Any additional context

`List.of()` is only valid for up to 10 arguments.

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?

yes

**Comment by timtebeek** [comment]
Probably best to close this issue to avoid confusion; it can be achieved through the following declarative recipe

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.timtebeek.ArraysAsListToListOf
displayName: ArraysAsListToListOf
description: ""
recipeList:
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: java.util.Arrays asList(..)
      fullyQualifiedTargetTypeName: java.util.List
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: java.util.List asList(..)
      newMethodName: of
```

That doesn't handle the modifiable part of the new returned type, but there's no good way to account for that in a recipe.
